package CRM.project.dto;

public enum MessagePreference {

    OPEN,
    RESOLVED,
    CLOSED,
    OTHERS,
    ADDITIONAL_INFORMATION,
    WORK_IN_PROGRESS,
    ON_HOLD,
    INITIATORCREATION,
    TECHNICIANCREATION,
    INITIATORRESOLUTION,
    TECHNICIANRESOLUTION,
    INITIATORCLOSURE,
    TECHNICIANCLOSURE;
}
