package CRM.project.dto;

public enum MessagePreference {

    OPEN,
    RESOLVED,
    CLOSED,
    INITIATORCREATION,
    TECHNICIANCREATION,
    INITIATORRESOLUTION,
    TECHNICIANRESOLUTION,
    INITIATORCLOSURE,
    TECHNICIANCLOSURE;
}
